name: Main job

on:
  push:
    tags:
      - v*.*.*

env:
  tag_version: ${{ secrets.DOCKER_USERNAME }}/docker-pulls-counter-test:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push an image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ env.tag_version }}